### PR TITLE
fix:fix project json to array

### PR DESCRIPTION
**Pull request by Piwriw**
fix:fix project json to array

issue：
https://github.com/goharbor/go-client/issues/26
https://github.com/goharbor/go-client/issues/25

### CODE REVIEW

**Comment by Piwriw** [comment]
@Vad1mo If there is no problem, I need you review

**Review by Vad1mo — APPROVED** [review]
looks ok to me, let me check with the others.

**Comment by Piwriw** [comment]
@Vad1mo I need more 2 approve,can u help me find others ?

**Comment by Piwriw** [comment]
Hi Vad1mo, just checking in to see if there are any updates on our previous discussion. Thanks!

**Comment by chlins** [comment]
The client code was generated by the swagger, the change will be reverted if re-make this project or upgrade the swagger yaml.

**Comment by Piwriw** [comment]
thanks,i get it

**Comment by Vad1mo** [comment]
can we now fix the swagger file to produce the correct result?

**Pull request closed without merging**
